### ISSUE TITLE
output with dune runtest could be improved

### ISSUE THREAD

**Issue by tcoopman** [janestreet/patdiff#10]
As you can see in this output:

![2018-09-25-162235_652x394](https://user-images.githubusercontent.com/45546/46020758-61738200-c0df-11e8-85a5-fec54e9cf112.png)

It would be nice if the actual difference on the last line was pointed out, the only difference is at the beginning `09` <> `10`

**Comment by bcc32** [comment]
Thanks for the suggestion!

I found out that the output when running `dune runtest` says that it's calling patdiff with the `-unrefined` flag, which turns off word-level diffs.

```
$ dune runtest
     patdiff (internal) (exit 1)
(cd _build/default && /bin/patdiff -keep-whitespace -location-style omake -unrefined test_temp.ml test_temp.ml.corrected)
```

I think this issue should be brought up in the dune repo, since the flag is working as intended on patdiff's part.
