### ISSUE TITLE
The git wrapper doesn't work inside emacs

### ISSUE THREAD

**Issue by billduff** [janestreet/patdiff#13]
Firstly, the install instructions don't work:
- I have no idea what the "where" command is (did you mean "which"?)
- Secondly, dune installs the git wrapper as patdiff-git-wrapper, not patdiff-git-wrapper.sh.

I worked around this by installing with `git config --global diff.external $(which patdiff-git-wrapper)`, but it doesn't actually seem to work with git. When I run `git diff <filename>` from within `M-x shell` in emacs it fails with "fatal: external diff died, stopping at \<filename\>".

My version of patdiff is v0.14.0, installed via opam.
My version of git is 2.17.1
I have PAGER=cat in my environment, though it also fails without that.

**Comment by bcc32** [comment]
`where` appears to be a tcsh/zsh-ism.  We should replace it with something more portable, like `command -v`; besides, it has the wrong semantics (it prints all available commands if there are multiple by that name).

Does the `git diff <filename>` command work for you outside of emacs?  I can't reproduce the failure either in a normal shell or in emacs.

I'm on git version 2.25.4, but I'm not clear on whether that might affect the behavior.

**Comment by bcc32** [comment]
Opened #14 to update the instructions.

**Comment by billduff** [comment]
Yeah, it works in normal bash, with and without PAGER=cat. My emacs version is "GNU Emacs 25.2.2"

**Comment by billduff** [comment]
Actually, I can't reproduce this in a fresh emacs.
