### ISSUE TITLE
Addition is considered as editing

### ISSUE THREAD

**Issue by mattiasdrp** [janestreet/patdiff#18]
When trying to patdiff the two following files:

`notmp`

    x: int

`tmp`

    x: int;
    tmp: int

I have the following output:

```
❯ patdiff diff/notmp diff/tmp
------ diff/notmp
++++++ diff/tmp
@|-1,1 +1,2 ============================================================
!|x: int;
!|tmp: int

```
When I was expecting to have:

```
❯ patdiff diff/notmp diff/tmp
------ diff/notmp
++++++ diff/tmp
@|-1,1 +1,2 ============================================================
!|x: int;
+|tmp: int
```

Because the `tmp: int` line was added

**Comment by bcc32** [comment]
Is this similar to #19, perhaps?  It's hard to tell what bug you're trying to point out because the GitHub issue does not have the color output that patdiff would have produced.

**Comment by mattiasdrp** [comment]
Yep, this is related (and I realised there was no coloration hence the screenshots in the following issues)
