### ISSUE TITLE
Add building instructions

### ISSUE THREAD

**Issue by danielcompton** [janestreet/patdiff#3]
I'd like to use this, but there aren't any instructions for building or what the dependencies are. Would you please be able to add a set of instructions for this?

**Comment by trefis** [comment]
We will include a README containing these information in the next release.
As for how one is supposed to build/install this, the **recommended** way nowadays is to use [opam](http://opam.ocaml.org/):
```
opam install patdiff
```

If for some reason you don't want to (or can't) use opam, you can simply check out the `release-113.00` branch and run the usual
```
make
make install
```
after installing the dependencies, which, [according to opam](http://opam.ocaml.org/packages/patdiff/patdiff.112.24.00/), are:
- camlp4
- core_extended
- patience_diff
- pcre

**Comment by bfontaine** [comment]
Is this still planned?

**Comment by xclerc** [comment]
Fixed by https://github.com/janestreet/patdiff/commit/c073c7a3a999cc274440fc5f80865657e443be9b.
