### ISSUE TITLE
Diff highlighting should probably avoid crossing whitespace when possible

### ISSUE THREAD

**Issue by jrmuizel** [janestreet/patdiff#4]
patdiff gives the following output (the first ! is not grouped with the change): 
http://people.mozilla.org/~jmuizelaar/tmp/diff-bad.html
but
http://people.mozilla.org/~jmuizelaar/tmp/diff-good.html
is preferred.

**Comment by bcc32** [comment]
Thanks for the bug report, and sorry it took so long to respond to this.  Unfortunately, it looks like those links are dead, and WayBack Machine doesn't have them archived either.  If you happen to still have those diffs, could you repost them somewhere or reply with an updated link?

**Comment by bcc32** [comment]
Closed due to inactivity.  Please open a new issue if you continue to experience this problem.
