### ISSUE TITLE
Make core_extended dependency optional

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [janestreet/patdiff#6]
I was trying to build patdiff from OPAM and it failed due to core\_extended failing. I was talking to @seliopou and he mentioned that core\_extended is only used for benchmarks.

Since I do not need the benchmarks, only the tool itself, I'd like to ask for the core\_extended dependency to be unbundled, since it increases compile time and has little benefit for the normal usage of patdiff itself.

**Comment by yminsky** [comment]
I'll take a look. If that's all it is, it shouldn't be hard to fix.

**Comment by yminsky** [comment]
Looking at it a moment longer, it doesn't look quite so trivial. patdiff depends on the file-finding functionality in Core_extended. That might make sense to break out to its own library, but it's not quite as trivial as @seliopou's comment suggests. Still, I'll take a look. Core_extended is kind of a mess, and breaking out useful functionality from there is generally a good thing.

**Comment by hhugo** [comment]
Note that patdiff also uses `Deprecated_command` from core_extended.

**Comment by seliopou** [comment]
I think this, at some point, was resolved.
